# -*- coding: utf-8 -*-
"""Secuencias de ADN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AgobM0jX9EmIfZ7GpyCJXLmN0wfkgo1i
"""

# secuencias_adn.py

secuencias_adn = {
    "Elefante": "ATGCGTACGATCGATCGTAGCTAG",
    "León": "ATGCTAGCTAGGCTAGGCTGAGCTA",
    "Tigre": "ATGCATCGTAGGCTGATCTAGTCGA",
    "Gato": "ATGCTAGCTAGCTGATCGTAGGCTA",
    "Perro": "ATGCATGCGTACGATCTAGGCTACG",
    "Panda": "ATGCTAGGCTAGCTGATGCTAGCTA",
    "Cebra": "ATGCGTACGTCGATGCTAGCTAGC",
    "Caballo": "ATGCGTACGTACGATCGTACGCTAG",
    "Ballena": "ATGCATGCTAGATCGGCTAAGCTGA",
    "Rana": "ATGCGTACGAGCTAGCTAGTCGATG",
}