# -*- coding: utf-8 -*-
"""TXT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W3LTs-8Y5HxKLVUhchBAb3mCTC3dJ63I
"""

streamlit
biopython
matplotlib
numpy